### PR TITLE
Add Rangers

### PR DESCRIPTION
**Pull request by mpariente**
As discussed in #64, just added the three Rangers as a dependency. 

For now, the params can't be tested because the error messages are not the same. Also, I could not make the `beale` test work for `Ranger`.

This is just a draft, feel free to push to my fork if you want to change the PR.

Regarding the docstrings and types, I wonder if it wouldn't be easier to sublass the optimizers here so that we can use the object in `types.py`. 
Or should I copy them there?

### CODE REVIEW

**Comment by jettify** [comment]
It is fine, just remove it from that test case. most important one is `test_optimizer.py`. That one is port from pytroch.

**Comment by mpariente** [comment]
Initially, I released `asranger` to be used in [`Asteroid`](https://github.com/mpariente/asteroid) only. Since it's going to be used here, I renamed it to `pytorch_ranger` which makes more sense. 

I wrote the type hints for `Ranger` (based on your types, I added a small note on the top of the file)and fixed the tests in `test_optimizer.py`. 
Both errored builds done seem related to the PR (looks like a failed connection)

**Comment by jettify** [comment]
@mpariente can you please downgrade python requirements to python3.5 to make CI green?

**Comment by mpariente** [comment]
Sorry, didn't see the it failed because of that. 
New release should fix it. 
And sorry for the four commits, my history got messed up but I saw you'll squash them.

**Pull request merged**
